/** Factory — returns a fresh state object for each Planimeter instance. */
export function createInitialState() {
    return {
        mode: 'draw',
        nextFeatureId: 1,
        selectedFeature: null,
        catastoSource: 'official',
        drawLockTimeoutId: null,
        isCtrlPressed: false,
        isDrawing: false,
        proxyHealthStatus: 'checking',
        proxyHealthMessage: '',
        proxyHealthRequestPending: false,
        proxyHealthIntervalId: null,
        persistenceSaveTimeoutId: null,
        persistenceMuted: false,
        locale: 'it',
        unitSystem: 'metric',
        toolbarPanel: 'operate',
        catastoOpacity: 0.9,
        catastoWmsLayers: ['CP.CadastralParcel'],
        parcelInfoEnabled: false,
        exportImageQuality: 'standard',
        cacheTtlDays: 30,
        cacheSizeMb: 500,
        parcelInfoLoading: false,
        parcelInfo: null,
        parcelInfoStatusKey: 'parcelInfo.disabled',
    };
}
